sudo: required
language: node_js
node_js:
  - "stable"

services:
  - docker
before_install:
  - docker build -t leoguoau/sample-app -f Dockerfile.dev .
script:
  - docker run -e CI=true leoguoau/sample-app npm run test -- --coverage --watchAll=false